package request;

import java.util.ArrayList;

import model.User;
import model.Person;
import model.Event;

/**
 * Request generated by the LoadHandler.
 */
public class LoadRequest extends Request {

    /** Array of users to be loaded */
    ArrayList<User> users;

    /** Array of persons to be loaded */
    ArrayList<Person> persons;

    /** Array of events to be loaded */
    ArrayList<Event> events;

    /** Parameterized constructor */
    public LoadRequest(ArrayList<User> users, ArrayList<Person> persons, ArrayList<Event> events) {
        this.users = users;
        this.persons = persons;
        this.events = events;
    }

    // Getters
    public ArrayList<User> getUsers() {
        return users;
    }

    public ArrayList<Person> getPersons() {
        return persons;
    }

    public ArrayList<Event> getEvents() {
        return events;
    }
}
