package request;

/**
 * Request generated by the LoginHandler.
 */
public class LoginRequest extends Request {

    /** Username of user requesting login */
    String userName;

    /** Password of user requesting login */
    String password;

    /** Parameterized constructor */
    public LoginRequest(String username, String password) {
        this.userName = username;
        this.password = password;
    }

    // Getters
    public String getUsername() {
        return userName;
    }

    public String getPassword() {
        return password;
    }
}
