package request;

/**
 * Request generated by the RegisterHandler.
 */
public class RegisterRequest extends Request {

    /** Username of user */
    String userName;

    /** Password of user */
    String password;

    /** Email of user */
    String email;

    /** First name of user */
    String firstName;

    /** Last name of user */
    String lastName;

    /** Gender of user */
    String gender;

    /** Default constructor */
    public RegisterRequest() {

    }

    /** Parameterized constructor */
    public RegisterRequest(String username, String password, String email, String firstName, String lastName, String gender) {
        this.userName = username;
        this.password = password;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
    }

    // Getters
    public String getUsername() {
        return userName;
    }

    public String getPassword() {
        return password;
    }

    public String getEmail() {
        return email;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getGender() {
        return gender;
    }
}
