package response;

/**
 * Error response generated by services.
 */
public class ErrorResponse extends Response {

    /** Message of why service is unsuccessful */
    private String message;
    
    /** Type of error */
    private String errorType;

    //Default constructor
    public ErrorResponse() {
    	
    }

    // Main constructor
    public ErrorResponse(String message, String errorType) {
        this.message = message;
        this.errorType = errorType;
    }

    public String getMessage() {
        return message;
    }
    
    public String getErrorType() {
    	return errorType;
    }
}
