package response;

/**
 * Error response generated by services.
 */
public class ErrorResponse extends GenericResponse {

    /** Message of why service is unsuccessful */
    private String message;

    //Default constructor
    public ErrorResponse() {

    }

    // Main constructor
    public ErrorResponse(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }
}
