package response;

import model.Event;

/**
 * Response generated by the EventService.
 */
public class EventResponse extends Response {

    /** Name of user account this event belongs to */
    private String descendant;

    /** Event's unique ID */
    private String eventID;

    /** ID of the person this event belongs to */
    private String personID;

    /** Latitude of the event's location */
    private double latitude;

    /** Longitude of the event's location */
    private double longitude;

    /** Name of country where event occurred */
    private String country;

    /** Name of city where event occurred */
    private String city;

    /** Type of event */
    private String eventType;

    /** Year the event occurred */
    private String year;

    /** Default constructor */
    public EventResponse() {

    }

    /** Parameterized constructor */
    public EventResponse(Event event) {
        this.descendant = event.getDescendant();
        this.eventID = event.getEventID();
        this.personID = event.getPersonID();
        this.latitude = event.getLatitude();
        this.longitude = event.getLongitude();
        this.country = event.getCountry();
        this.city = event.getCity();
        this.eventType = event.getEventType();
        this.year = event.getYear();
    }

}
