package response;

import model.Person;

/**
 * Response generated by the PersonService.
 */
public class PersonResponse extends GenericResponse {

    /** Name of user this Person belongs to */
    private String descendant;

    /** Unique identifier */
    private String personID;

    /** Person's first name */
    private String firstName;

    /** Person's last name */
    private String lastName;

    /** Person's gender */
    private String gender;

    /** ID of person's father */
    private String father;

    /** ID of person's mother */
    private String mother;

    /** ID of person's spouse */
    private String spouse;

    /** Default constructor */
    public PersonResponse() {

    }

    /** Single person constructor */
    public PersonResponse(Person person) {
        this.descendant = person.getDescendant();
        this.personID = person.getPersonID();
        this.firstName = person.getFirstName();
        this.lastName = person.getLastName();
        this.gender = person.getGender();
        this.father = person.getFather();
        this.mother = person.getMother();
        this.spouse = person.getSpouse();
    }

    public String getDescendant() {
        return descendant;
    }

    public String getPersonID() {
        return personID;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getGender() {
        return gender;
    }

    public String getFather() {
        return father;
    }

    public String getMother() {
        return mother;
    }

    public String getSpouse() {
        return spouse;
    }
}
