package response;

/**
 * Success response generated by services.
 */
public class SuccessResponse extends Response {

    /** Success message */
    private String message;

    /** Default constructor */
    public SuccessResponse() {

    }

    /** Main constructor */
    public SuccessResponse(String message) {
        this.message = message;
    }

    // Getter
    public String getMessage() {
        return message;
    }
}
